import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

// Migration 0002 is the constraint/index authority; these declarations provide typed access.
export const editorialArtifacts = sqliteTable('editorial_artifacts', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  artifactType: text('artifact_type').notNull(),
  currentVersionId: text('current_version_id'),
  status: text('status').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
  createdBy: text('created_by'),
  updatedBy: text('updated_by'),
  deletedAt: text('deleted_at'),
});
export const editorialArtifactVersions = sqliteTable('editorial_artifact_versions', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  artifactId: text('artifact_id').notNull(),
  versionNumber: integer('version_number').notNull(),
  parentVersionId: text('parent_version_id'),
  languageCode: text('language_code').notNull(),
  contentText: text('content_text'),
  contentJson: text('content_json'),
  sourceType: text('source_type').notNull(),
  intelligenceRunId: text('intelligence_run_id'),
  contentHash: text('content_hash').notNull(),
  wordCount: integer('word_count'),
  narrationRateProfileId: text('narration_rate_profile_id'),
  estimatedDurationSeconds: real('estimated_duration_seconds'),
  sourceScriptVersionId: text('source_script_version_id'),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by').notNull(),
});
export const artifactDependencies = sqliteTable('artifact_dependencies', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  sourceArtifactVersionId: text('source_artifact_version_id').notNull(),
  dependentArtifactVersionId: text('dependent_artifact_version_id').notNull(),
  dependencyType: text('dependency_type').notNull(),
  validityStatus: text('validity_status').notNull(),
  invalidatedAt: text('invalidated_at'),
  invalidatedByVersionId: text('invalidated_by_version_id'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const artifactApprovals = sqliteTable('artifact_approvals', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  artifactVersionId: text('artifact_version_id').notNull(),
  decision: text('decision').notNull(),
  actorId: text('actor_id').notNull(),
  actorRole: text('actor_role').notNull(),
  comment: text('comment'),
  decidedAt: text('decided_at').notNull(),
});
export const artifactStatusEvents = sqliteTable('artifact_status_events', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  artifactId: text('artifact_id').notNull(),
  artifactVersionId: text('artifact_version_id'),
  previousStatus: text('previous_status'),
  nextStatus: text('next_status').notNull(),
  reason: text('reason'),
  actorId: text('actor_id'),
  occurredAt: text('occurred_at').notNull(),
});
export const editorialRevisionRequests = sqliteTable('editorial_revision_requests', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  reviewedArtifactId: text('reviewed_artifact_id').notNull(),
  reviewedArtifactVersionId: text('reviewed_artifact_version_id').notNull(),
  reviewedArtifactRevision: integer('reviewed_artifact_revision').notNull(),
  targetStage: text('target_stage').notNull(),
  targetBaselineVersionId: text('target_baseline_version_id').notNull(),
  reasonCode: text('reason_code').notNull(),
  comment: text('comment'),
  status: text('status').notNull(),
  actorId: text('actor_id').notNull(),
  actorRole: text('actor_role').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  commandHash: text('command_hash').notNull(),
  auditEventId: text('audit_event_id').notNull(),
  createdAt: text('created_at').notNull(),
});
export const editorialRevisionRequestResolutions = sqliteTable(
  'editorial_revision_request_resolutions',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id').notNull(),
    projectId: text('project_id').notNull(),
    revisionRequestId: text('revision_request_id').notNull(),
    status: text('status').notNull(),
    resolutionArtifactVersionId: text('resolution_artifact_version_id').notNull(),
    resolutionEvidenceJson: text('resolution_evidence_json').notNull(),
    resolvedBy: text('resolved_by').notNull(),
    idempotencyKey: text('idempotency_key').notNull(),
    commandHash: text('command_hash').notNull(),
    auditEventId: text('audit_event_id').notNull(),
    resolvedAt: text('resolved_at').notNull(),
  },
);
export const editorialResearchRevisionImports = sqliteTable('editorial_research_revision_imports', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  revisionRequestId: text('revision_request_id').notNull(),
  researchArtifactId: text('research_artifact_id').notNull(),
  parentResearchVersionId: text('parent_research_version_id').notNull(),
  newResearchVersionId: text('new_research_version_id').notNull(),
  expectedArtifactRevision: integer('expected_artifact_revision').notNull(),
  actorId: text('actor_id').notNull(),
  actorRole: text('actor_role').notNull(),
  auditEventId: text('audit_event_id').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  commandHash: text('command_hash').notNull(),
  resultJson: text('result_json').notNull(),
  environment: text('environment').notNull(),
  createdAt: text('created_at').notNull(),
});
export const researchSources = sqliteTable('research_sources', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  researchVersionId: text('research_version_id').notNull(),
  sourceType: text('source_type').notNull(),
  title: text('title').notNull(),
  sourceUrl: text('source_url'),
  sourceReference: text('source_reference'),
  sourceKey: text('source_key'),
  sourceFingerprint: text('source_fingerprint'),
  contentHash: text('content_hash'),
  provenanceJson: text('provenance_json'),
  retrievedAt: text('retrieved_at'),
  publishedAt: text('published_at'),
  verificationStatus: text('verification_status').notNull(),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by').notNull(),
});
export const researchClaims = sqliteTable('research_claims', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  researchVersionId: text('research_version_id').notNull(),
  sourceId: text('source_id'),
  claimText: text('claim_text').notNull(),
  evidenceClass: text('evidence_class').notNull(),
  excerpt: text('excerpt'),
  confidence: real('confidence'),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by').notNull(),
});
export const ideaCandidates = sqliteTable('idea_candidates', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  artifactId: text('artifact_id').notNull(),
  artifactVersionId: text('artifact_version_id').notNull(),
  title: text('title').notNull(),
  angle: text('angle').notNull(),
  hook: text('hook').notNull(),
  rationale: text('rationale').notNull(),
  audienceJson: text('audience_json').notNull(),
  targetFormat: text('target_format').notNull(),
  targetPlatformsJson: text('target_platforms_json').notNull(),
  complexity: text('complexity'),
  monetizationCompatibility: text('monetization_compatibility'),
  risksJson: text('risks_json').notNull(),
  status: text('status').notNull(),
  recommendationRank: integer('recommendation_rank'),
  confidence: real('confidence'),
  evidenceClass: text('evidence_class').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
  createdBy: text('created_by').notNull(),
  updatedBy: text('updated_by').notNull(),
});
export const ideaScoreComponents = sqliteTable('idea_score_components', {
  id: text('id').primaryKey(),
  ideaCandidateId: text('idea_candidate_id').notNull(),
  dimension: text('dimension').notNull(),
  score: real('score'),
  confidence: real('confidence'),
  evidenceClass: text('evidence_class').notNull(),
  explanation: text('explanation').notNull(),
  createdAt: text('created_at').notNull(),
});
export const scriptSegments = sqliteTable('script_segments', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  scriptVersionId: text('script_version_id').notNull(),
  segmentOrder: integer('segment_order').notNull(),
  contentText: text('content_text').notNull(),
  contentHash: text('content_hash').notNull(),
  wordCount: integer('word_count').notNull(),
  estimatedDurationSeconds: real('estimated_duration_seconds'),
  createdAt: text('created_at').notNull(),
});
export const storyboardScenes = sqliteTable('storyboard_scenes', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  storyboardVersionId: text('storyboard_version_id').notNull(),
  sceneOrder: integer('scene_order').notNull(),
  targetDurationSeconds: real('target_duration_seconds'),
  visualDescription: text('visual_description').notNull(),
  location: text('location').notNull(),
  action: text('action').notNull(),
  cameraFraming: text('camera_framing').notNull(),
  cameraMovement: text('camera_movement'),
  aspectRatio: text('aspect_ratio'),
  safeAreaGuidanceJson: text('safe_area_guidance_json'),
  onScreenTextJson: text('on_screen_text_json'),
  captionsJson: text('captions_json'),
  factualClaimsJson: text('factual_claims_json'),
  mediaReferencesJson: text('media_references_json'),
  audioGuidanceJson: text('audio_guidance_json'),
  continuityKey: text('continuity_key'),
  continuityReferenceKeysJson: text('continuity_reference_keys_json'),
  contractVersion: text('contract_version'),
  mood: text('mood').notNull(),
  continuityNotes: text('continuity_notes').notNull(),
  generationInstructions: text('generation_instructions').notNull(),
  recommendedMediaType: text('recommended_media_type'),
  assetRequirementsJson: text('asset_requirements_json').notNull(),
  transitionNotes: text('transition_notes').notNull(),
  characterVersionRefsJson: text('character_version_refs_json').notNull(),
  createdAt: text('created_at').notNull(),
});
export const sceneScriptSegments = sqliteTable('scene_script_segments', {
  workspaceId: text('workspace_id').notNull(),
  storyboardSceneId: text('storyboard_scene_id').notNull(),
  scriptSegmentId: text('script_segment_id').notNull(),
  segmentOrder: integer('segment_order').notNull(),
  createdAt: text('created_at').notNull(),
});
export const narrationRateProfiles = sqliteTable('narration_rate_profiles', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  name: text('name').notNull(),
  languageCode: text('language_code').notNull(),
  wordsPerMinute: real('words_per_minute').notNull(),
  versionNumber: integer('version_number').notNull(),
  status: text('status').notNull(),
  sourceLabel: text('source_label').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by').notNull(),
});
export const preflightAssessments = sqliteTable('preflight_assessments', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  artifactId: text('artifact_id').notNull(),
  artifactVersionId: text('artifact_version_id').notNull(),
  overallResult: text('overall_result').notNull(),
  generationReadiness: text('generation_readiness').notNull(),
  ruleSetVersion: text('rule_set_version').notNull(),
  assessedAt: text('assessed_at').notNull(),
  assessedBy: text('assessed_by').notNull(),
});
export const preflightChecks = sqliteTable('preflight_checks', {
  id: text('id').primaryKey(),
  preflightAssessmentId: text('preflight_assessment_id').notNull(),
  checkKey: text('check_key').notNull(),
  result: text('result').notNull(),
  explanation: text('explanation').notNull(),
  evidenceJson: text('evidence_json').notNull(),
  ruleVersion: text('rule_version'),
  overrideAllowed: integer('override_allowed', { mode: 'boolean' }).notNull(),
  overrideActorId: text('override_actor_id'),
  overrideReason: text('override_reason'),
  createdAt: text('created_at').notNull(),
});
export const aiProviders = sqliteTable('ai_providers', {
  id: text('id').primaryKey(),
  key: text('key').notNull(),
  displayName: text('display_name').notNull(),
  status: text('status').notNull(),
  adapterVersion: text('adapter_version').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const aiProviderModels = sqliteTable('ai_provider_models', {
  id: text('id').primaryKey(),
  providerId: text('provider_id').notNull(),
  modelKey: text('model_key').notNull(),
  displayName: text('display_name').notNull(),
  status: text('status').notNull(),
  capabilitiesJson: text('capabilities_json').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const promptDefinitions = sqliteTable('prompt_definitions', {
  id: text('id').primaryKey(),
  key: text('key').notNull(),
  taskType: text('task_type').notNull(),
  description: text('description').notNull(),
  status: text('status').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const promptVersions = sqliteTable('prompt_versions', {
  id: text('id').primaryKey(),
  promptDefinitionId: text('prompt_definition_id').notNull(),
  versionNumber: integer('version_number').notNull(),
  templateText: text('template_text').notNull(),
  inputSchemaVersion: text('input_schema_version').notNull(),
  outputSchemaVersion: text('output_schema_version').notNull(),
  status: text('status').notNull(),
  contentHash: text('content_hash').notNull(),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by'),
});
export const intelligenceRuns = sqliteTable('intelligence_runs', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  taskType: text('task_type').notNull(),
  providerId: text('provider_id'),
  providerModelId: text('provider_model_id'),
  promptVersionId: text('prompt_version_id'),
  inputArtifactVersionId: text('input_artifact_version_id'),
  outputArtifactVersionId: text('output_artifact_version_id'),
  initiatedBy: text('initiated_by').notNull(),
  operatingMode: text('operating_mode').notNull(),
  status: text('status').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  creativeRegenerationNumber: integer('creative_regeneration_number').notNull(),
  safeMetadataJson: text('safe_metadata_json').notNull(),
  inputUnits: integer('input_units'),
  outputUnits: integer('output_units'),
  estimatedCost: real('estimated_cost'),
  actualCost: real('actual_cost'),
  currency: text('currency'),
  pricingSnapshotId: text('pricing_snapshot_id'),
  errorCategory: text('error_category'),
  safeErrorDetail: text('safe_error_detail'),
  terminalAuditEventId: text('terminal_audit_event_id'),
  startedAt: text('started_at'),
  completedAt: text('completed_at'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const intelligenceRunAttempts = sqliteTable('intelligence_run_attempts', {
  id: text('id').primaryKey(),
  intelligenceRunId: text('intelligence_run_id').notNull(),
  attemptNumber: integer('attempt_number').notNull(),
  attemptKind: text('attempt_kind').notNull(),
  status: text('status').notNull(),
  providerRequestId: text('provider_request_id'),
  safeMetadataJson: text('safe_metadata_json').notNull(),
  errorCategory: text('error_category'),
  safeErrorDetail: text('safe_error_detail'),
  startedAt: text('started_at').notNull(),
  completedAt: text('completed_at'),
});
export const aiPricingSnapshots = sqliteTable('ai_pricing_snapshots', {
  id: text('id').primaryKey(),
  providerModelId: text('provider_model_id').notNull(),
  currency: text('currency'),
  inputUnitPrice: real('input_unit_price'),
  outputUnitPrice: real('output_unit_price'),
  unitName: text('unit_name'),
  sourceLabel: text('source_label'),
  sourceUrl: text('source_url'),
  verificationStatus: text('verification_status').notNull(),
  effectiveFrom: text('effective_from').notNull(),
  effectiveTo: text('effective_to'),
  createdAt: text('created_at').notNull(),
  createdBy: text('created_by'),
});

export const editorialExecutionEnvelopes = sqliteTable('editorial_execution_envelopes', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  profileKey: text('profile_key').notNull(),
  profileVersion: integer('profile_version').notNull(),
  providerId: text('provider_id').notNull(),
  providerModelId: text('provider_model_id').notNull(),
  currency: text('currency').notNull(),
  monetaryCeilingMicrousd: integer('monetary_ceiling_microusd').notNull(),
  maximumCalls: integer('maximum_calls').notNull(),
  projectExecutionBudgetId: text('project_execution_budget_id'),
  stageKey: text('stage_key'),
  status: text('status').notNull(),
  authorizedBy: text('authorized_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});
export const editorialExecutionReservations = sqliteTable('editorial_execution_reservations', {
  id: text('id').primaryKey(),
  envelopeId: text('envelope_id').notNull(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  intelligenceRunId: text('intelligence_run_id').notNull(),
  stepKey: text('step_key').notNull(),
  pricingSnapshotId: text('pricing_snapshot_id').notNull(),
  reservedMicrousd: integer('reserved_microusd').notNull(),
  actualMicrousd: integer('actual_microusd'),
  status: text('status').notNull(),
  createdAt: text('created_at').notNull(),
  dispatchedAt: text('dispatched_at'),
  reconciledAt: text('reconciled_at'),
  projectExecutionBudgetId: text('project_execution_budget_id'),
});

export const editorialProjectExecutionBudgets = sqliteTable('editorial_project_execution_budgets', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  profileKey: text('profile_key').notNull(),
  profileVersion: integer('profile_version').notNull(),
  currency: text('currency').notNull(),
  monetaryCeilingMicrousd: integer('monetary_ceiling_microusd').notNull(),
  status: text('status').notNull(),
  authorizedBy: text('authorized_by').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
  version: integer('version').notNull(),
});

export const editorialExecutionRemediations = sqliteTable('editorial_execution_remediations', {
  id: text('id').primaryKey(),
  workspaceId: text('workspace_id').notNull(),
  projectId: text('project_id').notNull(),
  originalProjectExecutionBudgetId: text('original_project_execution_budget_id').notNull(),
  expectedOriginalBudgetVersion: integer('expected_original_budget_version').notNull(),
  historicalReservationId: text('historical_reservation_id').notNull(),
  historicalRunId: text('historical_run_id').notNull(),
  historicalEnvelopeId: text('historical_envelope_id').notNull(),
  remediationProjectExecutionBudgetId: text('remediation_project_execution_budget_id').notNull(),
  remediationEnvelopeId: text('remediation_envelope_id').notNull(),
  profileKey: text('profile_key').notNull(),
  profileVersion: integer('profile_version').notNull(),
  stageKey: text('stage_key').notNull(),
  providerId: text('provider_id').notNull(),
  providerModelId: text('provider_model_id').notNull(),
  additionalExposureMicrousd: integer('additional_exposure_microusd').notNull(),
  maximumCalls: integer('maximum_calls').notNull(),
  maximumAttempts: integer('maximum_attempts').notNull(),
  sdkMaxRetries: integer('sdk_max_retries').notNull(),
  fallbackEnabled: integer('fallback_enabled', { mode: 'boolean' }).notNull(),
  creativeRegenerationEnabled: integer('creative_regeneration_enabled', {
    mode: 'boolean',
  }).notNull(),
  externalResearchEnabled: integer('external_research_enabled', { mode: 'boolean' }).notNull(),
  humanApprovalRequired: integer('human_approval_required', { mode: 'boolean' }).notNull(),
  reasonCategory: text('reason_category').notNull(),
  idempotencyKey: text('idempotency_key').notNull(),
  commandHash: text('command_hash').notNull(),
  auditEventId: text('audit_event_id').notNull(),
  authorizedBy: text('authorized_by').notNull(),
  createdAt: text('created_at').notNull(),
});

export const editorialChainedExecutionRemediations = sqliteTable(
  'editorial_chained_execution_remediations',
  {
    id: text('id').primaryKey(),
    workspaceId: text('workspace_id').notNull(),
    projectId: text('project_id').notNull(),
    parentRemediationId: text('parent_remediation_id').notNull(),
    remediationGeneration: integer('remediation_generation').notNull(),
    historicalReservationId: text('historical_reservation_id').notNull(),
    historicalRunId: text('historical_run_id').notNull(),
    historicalEnvelopeId: text('historical_envelope_id').notNull(),
    remediationProjectExecutionBudgetId: text('remediation_project_execution_budget_id').notNull(),
    remediationEnvelopeId: text('remediation_envelope_id').notNull(),
    profileKey: text('profile_key').notNull(),
    profileVersion: integer('profile_version').notNull(),
    stageKey: text('stage_key').notNull(),
    providerId: text('provider_id').notNull(),
    providerModelId: text('provider_model_id').notNull(),
    additionalExposureMicrousd: integer('additional_exposure_microusd').notNull(),
    maximumCalls: integer('maximum_calls').notNull(),
    maximumAttempts: integer('maximum_attempts').notNull(),
    sdkMaxRetries: integer('sdk_max_retries').notNull(),
    fallbackEnabled: integer('fallback_enabled', { mode: 'boolean' }).notNull(),
    creativeRegenerationEnabled: integer('creative_regeneration_enabled', {
      mode: 'boolean',
    }).notNull(),
    externalResearchEnabled: integer('external_research_enabled', { mode: 'boolean' }).notNull(),
    humanApprovalRequired: integer('human_approval_required', { mode: 'boolean' }).notNull(),
    failureCategory: text('failure_category').notNull(),
    diagnosticCategory: text('diagnostic_category').notNull(),
    reasonCategory: text('reason_category').notNull(),
    idempotencyKey: text('idempotency_key').notNull(),
    commandHash: text('command_hash').notNull(),
    auditEventId: text('audit_event_id').notNull(),
    authorizedBy: text('authorized_by').notNull(),
    createdAt: text('created_at').notNull(),
  },
);
