PRAGMA foreign_keys = ON;

CREATE TABLE platforms (id TEXT PRIMARY KEY NOT NULL, key TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, status TEXT DEFAULT 'active' NOT NULL CHECK(status IN ('active','inactive')), capabilities_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(capabilities_json)), catalog_version INTEGER DEFAULT 1 NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL);
CREATE TABLE monetization_objectives (id TEXT PRIMARY KEY NOT NULL, key TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, description TEXT NOT NULL, status TEXT DEFAULT 'active' NOT NULL CHECK(status IN ('active','inactive')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL);
CREATE TABLE platform_monetization_programs (id TEXT PRIMARY KEY NOT NULL, platform_id TEXT NOT NULL REFERENCES platforms(id), key TEXT NOT NULL, display_name TEXT NOT NULL, status TEXT DEFAULT 'active' NOT NULL CHECK(status IN ('active','inactive')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, UNIQUE(platform_id,key));
CREATE TABLE platform_monetization_rule_versions (id TEXT PRIMARY KEY NOT NULL, program_id TEXT NOT NULL REFERENCES platform_monetization_programs(id), rule_version INTEGER NOT NULL, content_format TEXT NOT NULL CHECK(content_format IN ('SHORT','LONG_FORM')), minimum_duration_seconds INTEGER CHECK(minimum_duration_seconds IS NULL OR minimum_duration_seconds>0), maximum_duration_seconds INTEGER CHECK(maximum_duration_seconds IS NULL OR maximum_duration_seconds>0), constraints_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(constraints_json)), verification_status TEXT DEFAULT 'unverified' NOT NULL CHECK(verification_status IN ('unverified','owner_approved','externally_verified','stale','superseded')), source_label TEXT, source_url TEXT, verified_at TEXT, review_after TEXT, effective_from TEXT NOT NULL, effective_to TEXT, created_at TEXT NOT NULL, created_by TEXT, UNIQUE(program_id,rule_version,content_format));
CREATE TABLE platform_strategy_rule_versions (id TEXT PRIMARY KEY NOT NULL, platform_id TEXT NOT NULL REFERENCES platforms(id), objective_id TEXT NOT NULL REFERENCES monetization_objectives(id), source_platform_rule_id TEXT REFERENCES platform_monetization_rule_versions(id), strategy_version INTEGER NOT NULL, content_format TEXT NOT NULL CHECK(content_format IN ('SHORT','LONG_FORM')), priority INTEGER NOT NULL CHECK(priority>0), safety_margin_seconds INTEGER CHECK(safety_margin_seconds IS NULL OR safety_margin_seconds>=0), preferred_min_seconds INTEGER CHECK(preferred_min_seconds IS NULL OR preferred_min_seconds>0), preferred_max_seconds INTEGER CHECK(preferred_max_seconds IS NULL OR preferred_max_seconds>0), rationale TEXT NOT NULL, effective_from TEXT NOT NULL, effective_to TEXT, created_at TEXT NOT NULL, created_by TEXT, CHECK(preferred_min_seconds IS NULL OR preferred_max_seconds IS NULL OR preferred_min_seconds<=preferred_max_seconds), UNIQUE(platform_id,objective_id,content_format,strategy_version));

CREATE TABLE voice_profiles (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), name TEXT NOT NULL, primary_language TEXT NOT NULL, provider TEXT, provider_voice_ref TEXT, configuration_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(configuration_json) AND length(configuration_json)<=8192), status TEXT DEFAULT 'active' NOT NULL CHECK(status IN ('active','inactive','archived')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX voice_profiles_name_uq ON voice_profiles(workspace_id,name) WHERE deleted_at IS NULL;
CREATE TABLE character_profiles (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', status TEXT DEFAULT 'active' NOT NULL CHECK(status IN ('active','inactive','archived')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX character_profiles_name_uq ON character_profiles(workspace_id,name) WHERE deleted_at IS NULL;
CREATE TABLE character_profile_versions (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), character_profile_id TEXT NOT NULL REFERENCES character_profiles(id), version_number INTEGER NOT NULL CHECK(version_number>0), definition_json TEXT NOT NULL CHECK(json_valid(definition_json) AND length(definition_json)<=16384), created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), UNIQUE(character_profile_id,version_number));
CREATE TABLE content_brands (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), name TEXT NOT NULL, normalized_name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', niche TEXT NOT NULL DEFAULT '', primary_language TEXT NOT NULL, target_audience_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(target_audience_json) AND length(target_audience_json)<=8192), visual_style_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(visual_style_json) AND length(visual_style_json)<=8192), default_voice_profile_id TEXT REFERENCES voice_profiles(id), status TEXT DEFAULT 'draft' NOT NULL CHECK(status IN ('draft','active','archived')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX content_brands_name_uq ON content_brands(workspace_id,normalized_name) WHERE deleted_at IS NULL;
CREATE INDEX content_brands_list_idx ON content_brands(workspace_id,updated_at,id) WHERE deleted_at IS NULL;
CREATE TABLE channel_profiles (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), content_brand_id TEXT NOT NULL REFERENCES content_brands(id), name TEXT NOT NULL, normalized_name TEXT NOT NULL, primary_language TEXT NOT NULL, secondary_languages_json TEXT DEFAULT '[]' NOT NULL CHECK(json_valid(secondary_languages_json) AND length(secondary_languages_json)<=2048), narrative_tone TEXT NOT NULL DEFAULT '', editorial_strategy_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(editorial_strategy_json) AND length(editorial_strategy_json)<=8192), short_duration_min_seconds INTEGER CHECK(short_duration_min_seconds IS NULL OR short_duration_min_seconds>0), short_duration_max_seconds INTEGER CHECK(short_duration_max_seconds IS NULL OR short_duration_max_seconds>0), default_voice_profile_id TEXT REFERENCES voice_profiles(id), readiness_status TEXT DEFAULT 'draft' NOT NULL CHECK(readiness_status IN ('draft','configured','production_ready')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT, CHECK(short_duration_min_seconds IS NULL OR short_duration_max_seconds IS NULL OR short_duration_min_seconds<=short_duration_max_seconds));
CREATE UNIQUE INDEX channel_profiles_name_uq ON channel_profiles(workspace_id,content_brand_id,normalized_name) WHERE deleted_at IS NULL;
CREATE INDEX channel_profiles_brand_idx ON channel_profiles(workspace_id,content_brand_id) WHERE deleted_at IS NULL;
CREATE TABLE channel_profile_platforms (workspace_id TEXT NOT NULL REFERENCES workspaces(id), channel_profile_id TEXT NOT NULL REFERENCES channel_profiles(id), platform_id TEXT NOT NULL REFERENCES platforms(id), priority INTEGER NOT NULL CHECK(priority>0), preferences_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(preferences_json) AND length(preferences_json)<=4096), created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), PRIMARY KEY(channel_profile_id,platform_id));
CREATE TABLE channel_profile_characters (workspace_id TEXT NOT NULL REFERENCES workspaces(id), channel_profile_id TEXT NOT NULL REFERENCES channel_profiles(id), character_profile_id TEXT NOT NULL REFERENCES character_profiles(id), created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), PRIMARY KEY(channel_profile_id,character_profile_id));
CREATE TABLE channel_bibles (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), channel_profile_id TEXT NOT NULL REFERENCES channel_profiles(id), status TEXT DEFAULT 'draft' NOT NULL CHECK(status IN ('draft','approved','archived')), content_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(content_json) AND length(content_json)<=32768), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX channel_bibles_current_uq ON channel_bibles(channel_profile_id) WHERE deleted_at IS NULL;
CREATE TABLE social_accounts (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), channel_profile_id TEXT NOT NULL REFERENCES channel_profiles(id), platform_id TEXT NOT NULL REFERENCES platforms(id), display_name TEXT NOT NULL, handle TEXT, external_account_id TEXT, connection_status TEXT DEFAULT 'not_connected' NOT NULL CHECK(connection_status IN ('not_connected','pending','connected','error','disabled')), connection_method TEXT DEFAULT 'manual_reference' NOT NULL CHECK(connection_method='manual_reference'), capabilities_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(capabilities_json) AND length(capabilities_json)<=4096), last_connection_check_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX social_accounts_external_uq ON social_accounts(workspace_id,platform_id,external_account_id) WHERE external_account_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX social_accounts_channel_idx ON social_accounts(workspace_id,channel_profile_id,platform_id) WHERE deleted_at IS NULL;
CREATE TABLE social_account_monetization_statuses (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), social_account_id TEXT NOT NULL REFERENCES social_accounts(id), program_id TEXT NOT NULL REFERENCES platform_monetization_programs(id), status TEXT NOT NULL CHECK(status IN ('unknown','not_eligible','eligible','enrolled','suspended','restricted','not_applicable')), region TEXT, source_type TEXT NOT NULL CHECK(source_type IN ('observed','estimated','approved_default','unknown')), evidence_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(evidence_json) AND length(evidence_json)<=4096), effective_from TEXT NOT NULL, effective_to TEXT, reviewed_at TEXT, created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id));
CREATE UNIQUE INDEX social_account_monetization_current_uq ON social_account_monetization_statuses(social_account_id,program_id) WHERE effective_to IS NULL;

CREATE TABLE projects (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), content_brand_id TEXT NOT NULL REFERENCES content_brands(id), channel_profile_id TEXT NOT NULL REFERENCES channel_profiles(id), title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', format TEXT NOT NULL CHECK(format IN ('SHORT','LONG_FORM')), operating_mode TEXT DEFAULT 'ASSISTED' NOT NULL CHECK(operating_mode IN ('MANUAL','ASSISTED','AUTONOMOUS')), status TEXT DEFAULT 'DRAFT' NOT NULL CHECK(status IN ('DRAFT','ANALYZING','SCRIPT_REVIEW','STORYBOARD_REVIEW','PREFLIGHT_REVIEW','GENERATING','WAITING_APPROVAL','PACKAGE_READY','WAITING_FINAL_MASTER','FINAL_MASTER_PROCESSING','FINAL_REVIEW','READY_TO_PUBLISH','SCHEDULED','PUBLISHING','PUBLISHED','PAUSED','FAILED','CANCELLED')), primary_language TEXT NOT NULL, readiness_status TEXT DEFAULT 'configuring' NOT NULL CHECK(readiness_status IN ('configuring','ready')), archived_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE INDEX projects_list_idx ON projects(workspace_id,status,updated_at,id) WHERE deleted_at IS NULL;
CREATE TABLE project_objectives (workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), objective_id TEXT NOT NULL REFERENCES monetization_objectives(id), is_primary INTEGER DEFAULT 0 NOT NULL CHECK(is_primary IN (0,1)), priority INTEGER NOT NULL CHECK(priority>0), created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), PRIMARY KEY(project_id,objective_id));
CREATE UNIQUE INDEX project_primary_objective_uq ON project_objectives(project_id) WHERE is_primary=1;
CREATE TABLE project_targets (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), platform_id TEXT NOT NULL REFERENCES platforms(id), social_account_id TEXT REFERENCES social_accounts(id), priority INTEGER NOT NULL CHECK(priority>0), readiness_status TEXT DEFAULT 'not_connected' NOT NULL CHECK(readiness_status IN ('not_connected','account_unknown','ready','inactive')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX project_target_platform_uq ON project_targets(project_id,platform_id) WHERE social_account_id IS NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX project_target_account_uq ON project_targets(project_id,social_account_id) WHERE social_account_id IS NOT NULL AND deleted_at IS NULL;
CREATE TABLE project_variants (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), project_target_id TEXT REFERENCES project_targets(id), platform_id TEXT REFERENCES platforms(id), variant_kind TEXT NOT NULL CHECK(variant_kind IN ('MASTER','PLATFORM')), source_variant_id TEXT REFERENCES project_variants(id), status TEXT DEFAULT 'defined' NOT NULL CHECK(status IN ('defined','adaptation_required','ready','archived')), aspect_ratio TEXT, width INTEGER CHECK(width IS NULL OR width>0), height INTEGER CHECK(height IS NULL OR height>0), duration_seconds INTEGER CHECK(duration_seconds IS NULL OR duration_seconds>0), adaptation_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT, CHECK((variant_kind='MASTER' AND project_target_id IS NULL AND platform_id IS NULL AND source_variant_id IS NULL) OR (variant_kind='PLATFORM' AND project_target_id IS NOT NULL AND platform_id IS NOT NULL AND source_variant_id IS NOT NULL)));
CREATE UNIQUE INDEX project_master_variant_uq ON project_variants(project_id) WHERE variant_kind='MASTER' AND deleted_at IS NULL;
CREATE UNIQUE INDEX project_platform_variant_uq ON project_variants(project_target_id) WHERE variant_kind='PLATFORM' AND deleted_at IS NULL;
CREATE TABLE language_variants (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_variant_id TEXT NOT NULL REFERENCES project_variants(id), language_code TEXT NOT NULL, voice_profile_id TEXT REFERENCES voice_profiles(id), status TEXT DEFAULT 'defined' NOT NULL CHECK(status IN ('defined','ready','archived')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT);
CREATE UNIQUE INDEX language_variants_uq ON language_variants(project_variant_id,language_code) WHERE deleted_at IS NULL;
CREATE TABLE project_parameters (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), scope_type TEXT NOT NULL CHECK(scope_type IN ('project','target','variant','language_variant')), scope_id TEXT NOT NULL, parameter_key TEXT NOT NULL, policy_mode TEXT NOT NULL CHECK(policy_mode IN ('AUTO','PREFER','LOCKED')), requested_value_json TEXT CHECK(requested_value_json IS NULL OR json_valid(requested_value_json)), effective_value_json TEXT CHECK(effective_value_json IS NULL OR json_valid(effective_value_json)), recommendation_json TEXT CHECK(recommendation_json IS NULL OR json_valid(recommendation_json)), recommendation_source TEXT, recommendation_rule_version TEXT, deviation_reason TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER DEFAULT 1 NOT NULL, created_by TEXT REFERENCES users(id), updated_by TEXT REFERENCES users(id), deleted_at TEXT, CHECK(policy_mode!='LOCKED' OR requested_value_json IS NOT NULL));
CREATE UNIQUE INDEX project_parameters_scope_uq ON project_parameters(scope_type,scope_id,parameter_key) WHERE deleted_at IS NULL;
CREATE TABLE project_parameter_revisions (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_parameter_id TEXT NOT NULL REFERENCES project_parameters(id), revision_number INTEGER NOT NULL CHECK(revision_number>0), snapshot_json TEXT NOT NULL CHECK(json_valid(snapshot_json) AND length(snapshot_json)<=16384), changed_at TEXT NOT NULL, changed_by TEXT REFERENCES users(id), UNIQUE(project_parameter_id,revision_number));
CREATE TABLE project_dependencies (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), parent_project_id TEXT NOT NULL REFERENCES projects(id), child_project_id TEXT NOT NULL REFERENCES projects(id), relationship_type TEXT NOT NULL CHECK(relationship_type='LONG_FORM_TO_SHORT'), created_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), CHECK(parent_project_id!=child_project_id), UNIQUE(parent_project_id,child_project_id,relationship_type));
CREATE TABLE monetization_eligibility_assessments (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), project_target_id TEXT NOT NULL REFERENCES project_targets(id), platform_rule_id TEXT REFERENCES platform_monetization_rule_versions(id), strategy_rule_id TEXT REFERENCES platform_strategy_rule_versions(id), publishable INTEGER NOT NULL CHECK(publishable IN (0,1)), program_rule_match INTEGER CHECK(program_rule_match IN (0,1) OR program_rule_match IS NULL), account_eligible INTEGER CHECK(account_eligible IN (0,1) OR account_eligible IS NULL), monetization_eligible INTEGER CHECK(monetization_eligible IN (0,1) OR monetization_eligible IS NULL), reasons_json TEXT DEFAULT '[]' NOT NULL CHECK(json_valid(reasons_json)), inputs_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(inputs_json)), evaluated_at TEXT NOT NULL, created_by TEXT REFERENCES users(id));
CREATE INDEX eligibility_project_idx ON monetization_eligibility_assessments(workspace_id,project_id,evaluated_at);
CREATE TABLE opportunity_assessments (id TEXT PRIMARY KEY NOT NULL, workspace_id TEXT NOT NULL REFERENCES workspaces(id), project_id TEXT NOT NULL REFERENCES projects(id), project_target_id TEXT REFERENCES project_targets(id), score REAL CHECK(score IS NULL OR (score>=0 AND score<=100)), expected_revenue REAL, inputs_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(inputs_json)), explanation_json TEXT DEFAULT '{}' NOT NULL CHECK(json_valid(explanation_json)), model_version TEXT NOT NULL, assessed_at TEXT NOT NULL, created_by TEXT REFERENCES users(id), CHECK(expected_revenue IS NULL OR expected_revenue>=0));

CREATE TRIGGER platform_rules_no_update BEFORE UPDATE ON platform_monetization_rule_versions BEGIN SELECT RAISE(ABORT,'platform rule versions are immutable'); END;
CREATE TRIGGER platform_rules_no_delete BEFORE DELETE ON platform_monetization_rule_versions BEGIN SELECT RAISE(ABORT,'platform rule versions are immutable'); END;
CREATE TRIGGER strategy_rules_no_update BEFORE UPDATE ON platform_strategy_rule_versions BEGIN SELECT RAISE(ABORT,'strategy rule versions are immutable'); END;
CREATE TRIGGER strategy_rules_no_delete BEFORE DELETE ON platform_strategy_rule_versions BEGIN SELECT RAISE(ABORT,'strategy rule versions are immutable'); END;
CREATE TRIGGER eligibility_assessments_no_update BEFORE UPDATE ON monetization_eligibility_assessments BEGIN SELECT RAISE(ABORT,'eligibility assessments are immutable'); END;
CREATE TRIGGER eligibility_assessments_no_delete BEFORE DELETE ON monetization_eligibility_assessments BEGIN SELECT RAISE(ABORT,'eligibility assessments are immutable'); END;

INSERT INTO platforms(id,key,display_name,status,capabilities_json,catalog_version,created_at,updated_at,version) VALUES
('platform_tiktok','tiktok','TikTok','active','{"short":true,"longForm":false}',1,datetime('now'),datetime('now'),1),
('platform_facebook','facebook','Facebook','active','{"short":true,"longForm":true}',1,datetime('now'),datetime('now'),1),
('platform_youtube','youtube','YouTube','active','{"short":true,"longForm":true}',1,datetime('now'),datetime('now'),1),
('platform_instagram','instagram','Instagram','active','{"short":true,"longForm":false}',1,datetime('now'),datetime('now'),1);
INSERT INTO monetization_objectives(id,key,display_name,description,status,created_at,updated_at,version) VALUES
('objective_reach','reach','Reach','Maximize qualified reach','active',datetime('now'),datetime('now'),1),('objective_audience_growth','audience_growth','Audience growth','Grow the relevant audience','active',datetime('now'),datetime('now'),1),('objective_engagement','engagement','Engagement','Encourage meaningful engagement','active',datetime('now'),datetime('now'),1),('objective_monetization','monetization','Monetization','Optimize for eligible monetization opportunities','active',datetime('now'),datetime('now'),1),('objective_conversion','conversion','Conversion','Support a defined conversion outcome','active',datetime('now'),datetime('now'),1),('objective_brand_building','brand_building','Brand building','Build long-term brand value','active',datetime('now'),datetime('now'),1);
INSERT INTO platform_monetization_programs(id,platform_id,key,display_name,status,created_at,updated_at,version) VALUES ('program_tiktok_creator_rewards','platform_tiktok','creator_rewards','TikTok Creator Rewards','active',datetime('now'),datetime('now'),1);
INSERT INTO platform_monetization_rule_versions(id,program_id,rule_version,content_format,minimum_duration_seconds,constraints_json,verification_status,source_label,effective_from,created_at) VALUES ('platform_rule_tiktok_creator_rewards_v1','program_tiktok_creator_rewards',1,'SHORT',60,'{}','unverified','Phase 2 baseline pending formal source verification','2026-09-03',datetime('now'));
INSERT INTO platform_strategy_rule_versions(id,platform_id,objective_id,source_platform_rule_id,strategy_version,content_format,priority,safety_margin_seconds,preferred_min_seconds,preferred_max_seconds,rationale,effective_from,created_at) VALUES
('strategy_short_tiktok_v1','platform_tiktok','objective_monetization','platform_rule_tiktok_creator_rewards_v1',1,'SHORT',1,5,65,90,'VISION MAXSON internal safety and duration preference; not a platform guarantee','2026-09-03',datetime('now')),
('strategy_short_facebook_v1','platform_facebook','objective_monetization',NULL,1,'SHORT',2,NULL,NULL,NULL,'VISION MAXSON initial strategic priority; not an RPM ranking','2026-09-03',datetime('now')),
('strategy_short_youtube_v1','platform_youtube','objective_monetization',NULL,1,'SHORT',3,NULL,NULL,NULL,'VISION MAXSON initial strategic priority; not an RPM ranking','2026-09-03',datetime('now')),
('strategy_short_instagram_v1','platform_instagram','objective_monetization',NULL,1,'SHORT',4,NULL,NULL,NULL,'VISION MAXSON initial strategic priority; not an RPM ranking','2026-09-03',datetime('now')),
('strategy_long_youtube_v1','platform_youtube','objective_monetization',NULL,1,'LONG_FORM',1,NULL,NULL,NULL,'VISION MAXSON default long-form platform strategy','2026-09-03',datetime('now'));
